import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FlagProvider } from "@unleash/nextjs/client";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sessionId =
    cookies().get("unleash")?.value ||
    `${Math.floor(Math.random() * 1_000_000_000)}`;

  return (
    <FlagProvider config={{ context: { sessionId } }}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </FlagProvider>
  );
}
